name: CI

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: version
        run: |
          python3 --version
      - name: run
        run: |
          ./repro.py

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: version
        run: |
          python3 --version
      - name: run
        run: |
          ./repro.py
